### ISSUE TITLE
Create button for team leader to create team

### ISSUE THREAD

**Issue by IonutNechita01** [Evelyne03/Proiect-Colectiv#12]
facem butonul pentru leader pentru crearea echipei, acest buton dispare daca leader ul are o echipa creata, butonul de tuce la pagina de creare unde vom face un form cu numele echipei si posibilitatea de a adauga membrii, un search bar ma gandeam eu, sau poate un drop box

**Comment by HoalbaDarius** [comment]
Cand se creeaza un cont de teamleader automat se creeaza o echipa si i se asociaza. Similar cu ce se intampla la creearea unui Task cand se instantiaza si un mentor grade

![image](https://github.com/Evelyne03/Proiect-Colectiv/assets/89664541/51129fc3-5e2d-4207-be44-09ea0cb4f393)

Putem sa ii dam echipei un nume by default si teamlead-ul sa aiba un buton de manage team de unde sa editeze nume si useri

**Comment by IonutNechita01** [comment]
bine atunci, numele default sa fie leader name + "Team"

**Comment by HoalbaDarius** [comment]
Rezolvat, cand se inregistreaza un User ca "teamleader" se creaza automat si echipa
