### ISSUE TITLE
Remove current user from "see all users" and disable delete icon from mentor cards

### ISSUE THREAD

**Issue by IonutNechita01** [Evelyne03/Proiect-Colectiv#5]
Ar trebui sa scoate posibilitatea ca un mentor sa stearga alt mentor, si nici sa nu se vada pe el insusi

**Comment by HoalbaDarius** [comment]
![image](https://github.com/Evelyne03/Proiect-Colectiv/assets/89664541/eef2816a-d37a-423e-af4b-0feba946ca47)
Done
