### ISSUE TITLE
Hide the "See my students" button for mentors who haven't a team

### ISSUE THREAD

**Issue by IonutNechita01** [Evelyne03/Proiect-Colectiv#8]
sa ascundem butonul "see my students" pentru mentorii care inca nu si au selectat echipa

**Comment by HoalbaDarius** [comment]
Aici am putea fie sa ascundem butonul fie sa avem o a 2-a interfata in care sa isi poata selecta echipa dintre cele fara mentor.

**Comment by IonutNechita01** [comment]
si asa merge, si nu mai facem button separat pentru see all teams, facem buttonul asta sa faca asta in functie de starea mentorului adica daca are sau nu echipa, il poti face tu si pe asta?

**Comment by HoalbaDarius** [comment]
Done
